In [ ]:
angka = [1, 2, 3, 4]
print(angka)

[1, 2, 3, 4]


In [ ]:
import numpy as np
angka = np.array([1, 2, 3, 4])
print(angka)

[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

(2, 3)
6
2


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

total = a + b
print(total)

[5 7 9]


In [ ]:
nilai = np.array([70,80,90])
nilai + 10
total = nilai + 10
print(total)

[ 80  90 100]


In [ ]:
nilai = np.array([70,80,90])
nilai *2
total = nilai *2
print(total)

[140 160 180]


In [ ]:
nilai = np.array([70,80,90,85,95])

rata_rata = np.mean(nilai)
maksimum = np.max(nilai)
minimum = np.min(nilai)
jumlah = np.sum(nilai)

print(rata_rata)
print(maksimum)
print(minimum)
print(jumlah)


84.0
95
70
420


In [ ]:
import numpy as np
nilai = np.array([67,68,70,65,90,97,77,45,75])
kkm = 70

lulus = np.sum(nilai >= kkm)
print(lulus)
tidak_lulus = np.sum(nilai < kkm)
print(tidak_lulus)
nilai_terbesar_kedua = list(set(nilai))
nilai_terbesar_kedua.sort(reverse = True)
print(nilai_terbesar_kedua[3])

5
4
75


In [ ]:
nilai = np.array([55,67,34,45,34,75])
duplicate = []
for x in nilai:
  if x not in nilai:
    duplicate.append(x)
print(duplicate)

[]


In [ ]:
nilai = np.array([67,68,70,65,90,97,77,45,75,78,88,74,60])

print(nilai.shape)
print(nilai.size)
print(nilai.ndim)

nilai*4
total = nilai*4
print(total)

rata_rata = np.mean(nilai)
maksimum = np.max(nilai)
minimum = np.min(nilai)
jumlah = np.sum(nilai)

print(rata_rata)
print(maksimum)
print(minimum)
print(jumlah)

kkm = 73
lulus = np.sum(nilai >= kkm)
print(lulus)
tidak_lulus = np.sum(nilai < kkm)
print(tidak_lulus)

(13,)
13
1
[268 272 280 260 360 388 308 180 300 312 352 296 240]
73.38461538461539
97
45
954
7
6


In [ ]:
nilai = (50,78,67,45,90,89)

kkm = 75
nilai = 89
if nilai >= 75:
  print("lulus")
else:
  print("tidak lulus")

lulus
